site_name: NumericPHP Documentation
site_url: https://numpower.readthedocs.io
site_description: Documentation for NumPower, a Python library for numerical computations.
site_author: Rasaq Lawani
theme:
  name: material
  logo: assets/logo.png
  palette:
    primary: 'black'
    accent: 'blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs        # Enables top navigation tabs
    - navigation.tabs.sticky 
nav:
  - Getting Started: index.md
  - User Guide: user_guide.md
  - API Reference: api_reference.md
